// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/julioshinoda/api/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetOperationTypeByID provides a mock function with given fields: id
func (_m *Repository) GetOperationTypeByID(id int32) (models.OperationType, error) {
	ret := _m.Called(id)

	var r0 models.OperationType
	if rf, ok := ret.Get(0).(func(int32) models.OperationType); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.OperationType)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
