// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/julioshinoda/api/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: transaction
func (_m *Repository) Create(transaction models.Transaction) (models.Transaction, error) {
	ret := _m.Called(transaction)

	var r0 models.Transaction
	if rf, ok := ret.Get(0).(func(models.Transaction) models.Transaction); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Get(0).(models.Transaction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Transaction) error); ok {
		r1 = rf(transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
